In [1]:
import pandas as pd 
import numpy as np

In [2]:
sheets = ["Y10", "Y11", "Y12", "Y13", "Y14", "Y15", "Y16", "Y17", "Y18"]
master_df = pd.DataFrame(columns=['Segment', 'Category', 'Region', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'AVG'])
for sheet in sheets:
    Y_df = pd.read_excel("Ind41_CIR.xlsx", sheet)
    headers = Y_df.iloc[0]
    intial_columns_df = pd.DataFrame(Y_df.values[1:], columns=headers).iloc[0:52, 0:3]
    intial_columns_df.columns.values[0] = "Segment"
    intial_columns_df.columns.values[1] = "Category"
    intial_columns_df.columns.values[2] = "Region"
    intial_columns_df["Year"] = sheet

    new_df  = pd.DataFrame(Y_df.values[1:], columns=headers)
    df0 = new_df.iloc[0:52, 3:16]
    df1 = new_df.iloc[0:52, 17:30]
    df2 = new_df.iloc[0:52, 31:44]
    df3 = new_df.iloc[0:52, 45:58]

    df0 = pd.concat([intial_columns_df, df0], axis=1)
    df0["Region"] = "NorthA"
    df0["Segment"][0:19] = "INTERNET"
    df0["Segment"][20:42] = "WHOLESALE"
    df0["Segment"][43:51] = "PRIVATELABEL"

    df1 = pd.concat([intial_columns_df, df1], axis=1)
    df1["Region"] = "EP"
    df1["Segment"][0:19] = "INTERNET"
    df1["Segment"][20:42] = "WHOLESALE"
    df1["Segment"][43:51] = "PRIVATELABEL"

    df2 = pd.concat([intial_columns_df, df2], axis=1)
    df2["Region"] = "AP"
    df2["Segment"][0:19] = "INTERNET"
    df2["Segment"][20:42] = "WHOLESALE"
    df2["Segment"][43:51] = "PRIVATELABEL"

    df3 = pd.concat([intial_columns_df, df3], axis=1)
    df3["Region"] = "LA"
    df3["Segment"][0:19] = "INTERNET"
    df3["Segment"][20:42] = "WHOLESALE"
    df3["Segment"][43:51] = "PRIVATELABEL"

    master_df = pd.concat([master_df, df0, df1, df2, df3])

master_df

,Segment,Category,Region,A,B,C,D,E,F,G,H,I,J,K,L,AVG,Year
0,INTERNET,NaN,NorthA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y10
1,INTERNET,NaN,NorthA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y10
2,INTERNET,Retail Price ($ per pair),NorthA,67,67,67,67,67,67,67,67,67,67,67,67,67,Y10
3,INTERNET,Search Engine Advert. ($000s),NorthA,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,Y10
4,INTERNET,Free Shipping,NorthA,0,0,0,0,0,0,0,0,0,0,0,0,0,Y10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,PRIVATELABEL,Pairs Sold (000s),LA,0,995,0,1003,0,0,0,0,0,0,0,0,2677,Y18
48,PRIVATELABEL,Market Share (%),LA,0,0.496,0,0.5,0,0,0,0,0,0,0,0,1998,Y18
49,PRIVATELABEL,,LA,,,,,,,,,,,,,,Y18
50,PRIVATELABEL,,LA,,,,,,,,,,,,,,Y18
51,NaN,,LA,,,,,,,,,,,,,,Y18

In [3]:
master_df = master_df.replace(r'^\s*$', np.nan, regex=True)
master_df = master_df.dropna(axis=0)

In [4]:
master_df

,Segment,Category,Region,A,B,C,D,E,F,G,H,I,J,K,L,AVG,Year
2,INTERNET,Retail Price ($ per pair),NorthA,67.00,67.000,67.00,67.00,67.0,67.0,67.0,67.0,67.0,67.0,67.0,67.0,67.0,Y10
3,INTERNET,Search Engine Advert. ($000s),NorthA,5000.00,5000.000,5000.00,5000.00,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,Y10
4,INTERNET,Free Shipping,NorthA,0.00,0.000,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Y10
6,INTERNET,S/Q Rating (1 to 10 stars),NorthA,4.00,4.000,4.00,4.00,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,Y10
7,INTERNET,Model Availability,NorthA,200.00,200.000,200.00,200.00,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,Y10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,PRIVATELABEL,Offer Price (max = $40.00),LA,43.69,39.000,59.98,39.49,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67.5,Y18
44,PRIVATELABEL,S/Q Rating (min = 3.0 stars),LA,5.50,5.000,5.00,5.10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,Y18
46,PRIVATELABEL,Pairs Offered (000s),LA,383.00,995.000,296.00,1003.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2008.0,Y18
47,PRIVATELABEL,Pairs Sold (000s),LA,0.00,995.000,0.00,1003.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2677.0,Y18
48,PRIVATELABEL,Market Share (%),LA,0.00,0.496,0.00,0.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1998.0,Y18

In [5]:
master_df.to_excel("processed_CIR.xlsx")